# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEVOPS_DIR: automation

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  start-validation:
    name: Start Validation
    runs-on: ubuntu-latest
    steps:
    - name: Check-out devops repository
      uses: actions/checkout@v3
      with:
        repository: mhaynes762/yaml_templating
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.DEVOPS_DIR }}

    - name: Validate
      run: python ${{ env.DEVOPS_DIR }}/start.py
      shell: sh
